#!/bin/bash
# Test Bedrock Agent Core Runtime - DNS Lookup Service

echo "🧪 Testing Bedrock Agent Core - DNS Lookup Service"
echo ""

# Configuration
REGION=${AWS_DEFAULT_REGION:-"us-east-1"}

# Try to find your agent
echo "🔍 Finding your Bedrock Agent..."
aws bedrock-agent list-agents --region $REGION --query 'agentSummaries[*].[agentName,agentId,agentStatus]' --output table 2>/dev/null || echo "❌ Unable to list agents - check permissions"

echo ""
echo "📋 Manual Testing Steps:"
echo ""
echo "1. Get Agent Details from AWS Console:"
echo "   → Go to Amazon Bedrock Console"
echo "   → Navigate to 'Agents'"
echo "   → Find your DNS lookup agent"
echo "   → Note the Agent ID and Alias ID"
echo ""
echo "2. Test via Bedrock Console:"
echo "   → In your agent page, click 'Test'"
echo "   → Try these prompts:"
echo "     • 'Look up DNS records for aws.amazon.com'"
echo "     • 'What is the IP address of google.com?'"
echo "     • 'Resolve DNS for github.com'"
echo ""
echo "3. Test via API (if you have the agent details):"
echo "   Replace {AGENT-ID}, {ALIAS-ID}, {SESSION-ID} with your values:"
echo ""
echo "   curl -X POST \\"
echo "     'https://bedrock-agent-runtime.${REGION}.amazonaws.com/agents/{AGENT-ID}/agentAliases/{ALIAS-ID}/sessions/{SESSION-ID}/text' \\"
echo "     -H 'Authorization: AWS4-HMAC-SHA256 {your-sig}' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"inputText\": \"Look up DNS records for aws.amazon.com\""
echo "     }'"
echo ""
echo "4. Test via AWS CLI (easier):"
echo "   aws bedrock-agent-runtime invoke-agent \\"
echo "     --agent-id {AGENT-ID} \\"
echo "     --agent-alias-id {ALIAS-ID} \\"
echo "     --session-id test-session-$(date +%s) \\"
echo "     --input-text 'Look up DNS records for aws.amazon.com' \\"
echo "     --region ${REGION} \\"
echo "     response.json"
echo ""
echo "📝 Expected Agent Response:"
echo "   The agent should respond with DNS record information"
echo "   showing IP addresses and record types for the requested domain"
echo ""
echo "🔧 If Testing Fails:"
echo "   1. Check agent status is 'PREPARED' or 'ACTIVE'"
echo "   2. Verify action groups are configured correctly"
echo "   3. Check CloudWatch logs for your agent"
echo "   4. Ensure your container action is properly mapped"